.TH "md__r_e_a_d_m_e" 3 "Segunda, 24 de Agosto de 2020" "JVM - Java Virtual Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- JVM 
Uma implementação simples de uma Máquina Virtual Java\&.
.SH "WorkFlow"
.PP
.IP "\(bu" 2
Criar uma \fBnova issue\fP para uma situação ou escolher uma existente\&.
.IP "\(bu" 2
Criar um \fBnovo branch\fP para cada nova \fBissue\fP, apagar a branch quando terminar a implementação\&.
.IP "\(bu" 2
Ao terminar a implementação, fazer um \fBpull request\fP para a master, delegar o \fIPR\fP para outra pessoa\&.
.PP
.SH "Padrão de codificação"
.PP
.IP "\(bu" 2
Separar nomes de atributos, métodos ou classes por \fBcaixa alta/baixa\fP e não por underline\&. 
.PP

